spring:
  application:
    name: commentArea
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc
    username: root
    password: 1111
  security:
    filter:
      order: -100
    jwt:
      key: abcdefgjk
      expire: 7
server:
  # 绑定所有网卡，局域网可见
  address: 0.0.0.0
  # 端口自定义，避免冲突
  port: 8081